version: '2'

services:
  trans:
    image: linuxserver/transmission
    volumes:
      - '/docker/config/trans:/config'
      - '/docker/dl/downloads:/downloads'
      - '/docker/dl/watch:/watch'
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    expose:
      - "51413"
    environment:
      VIRTUAL_HOST: trans.trilogyphoto.co.uk
      VIRTUAL_PORT: 9091
    restart: always

  cp:
    image: linuxserver/couchpotato
    volumes:
      - '/docker/config/cp/:/config/'
      - '/docker/dl/cp/downloads/:/downloads/'
      - '/docker/dl/downloads/complete/:/movies/'
    expose:
      - 5050
    environment:
      - PGID=1001
      - PUID=1001
      - TZ=Europe/London
    environment:
      VIRTUAL_HOST: cp.trilogyphoto.co.uk

networks:
  default:
    external:
      name: pn

